# Generated by Django 5.1.7 on 2025-04-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='retaurant',
            new_name='restaurant',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='picture',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1147/1147856.png'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='delivery.customer')),
                ('items', models.ManyToManyField(related_name='carts', to='delivery.menuitem')),
            ],
        ),
    ]
